<?php

namespace App\Admin\Http\Requests\Contract;

use App\Http\Requests\Request;

class ContractRequest extends Request
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    protected function methodPost()
    {
        return [
            'admin_id' => ['required', 'exists:App\Models\Admin,id'],
            'code' => ['required', 'string'],
            'name' => ['required', 'string'],
            'type' => ['required'],
            'rental_land_code' => ['nullable'],
            'rental_land_title' => ['nullable'],
            'rental_land_address' => ['nullable'],
            'rental_date_create' => ['nullable'],
            'rental_owner_fullname' => ['nullable'],
            'rental_owner_phonenumber' => ['nullable'],
            'rental_owner_id_number' => ['nullable'],
            'rental_owner_id_date' => ['nullable'],
            'rental_owner_id_location' => ['nullable'],
            'rental_owner_location' => ['nullable'],
            'rental_customer_fullname' => ['nullable'],
            'rental_customer_phonenumber' => ['nullable'],
            'rental_customer_id_number' => ['nullable'],
            'rental_customer_id_date' => ['nullable'],
            'rental_customer_id_location' => ['nullable'],
            'rental_customer_location' => ['nullable'],
            'rental_customer_company' => ['nullable'],
            'rental_customer_address' => ['nullable'],
            'rental_customer_code' => ['nullable'],
            'rental_customer_position' => ['nullable'],
            'rental_customer_phone' => ['nullable'],
            'rental_customer_email' => ['nullable'],
            'rental_customer_represent' => ['nullable'],
            'rental_performer_represent' => ['nullable'],
            'rental_performer_position' => ['nullable'],
            'rental_performer_fullname' => ['nullable'],
            'rental_purpose' => ['nullable'],
            'rental_purpose_lang' => ['nullable'],
            'rental_time' => ['nullable'],
            'rental_time_start' => ['nullable'],
            'rental_price_vnd' => ['nullable'],
            'rental_price_text' => ['nullable'],
            'rental_price_usd' => ['nullable'],
            'rental_price_usd_text' => ['nullable'],
            'rental_price_kr' => ['nullable'],
            'rental_price_kr_text' => ['nullable'],
            'rental_month_earnest' => ['nullable'],
            'rental_month_pay' => ['nullable'],
            'rental_pay_start' => ['nullable'],
            'rental_pay_end' => ['nullable'],
            'rental_condition' => ['nullable'],

            'transfer_date_create' => ['nullable'],
            'transfer_owner_fullname' => ['nullable'],
            'transfer_owner_id_number' => ['nullable'],
            'transfer_owner_id_date' => ['nullable'],
            'transfer_owner_id_location' => ['nullable'],
            'transfer_owner_address' => ['nullable'],
            'transfer_owner_bank' => ['nullable'],
            'transfer_land_title' => ['nullable'],
            'transfer_land_code' => ['nullable'],
            'transfer_land_address' => ['nullable'],
            'transfer_customer_fullname' => ['nullable'],
            'transfer_customer_id_number' => ['nullable'],
            'transfer_customer_id_date' => ['nullable'],
            'transfer_customer_id_location' => ['nullable'],
            'transfer_customer_address' => ['nullable'],
            'transfer_performer_represent' => ['nullable'],
            'transfer_performer_position' => ['nullable'],
            'transfer_performer_fullname' => ['nullable'],
            'transfer_land_area' => ['nullable'],
            'transfer_land_certification_number' => ['nullable'],
            'transfer_land_certification_input_number' => ['nullable'],
            'transfer_land_number' => ['nullable'],
            'transfer_land_map_number' => ['nullable'],
            'transfer_land_certification_date' => ['nullable'],
            'transfer_price_number' => ['nullable'],
            'transfer_price_text' => ['nullable'],
            'transfer_payment1_date' => ['nullable'],
            'transfer_payment1_price_number' => ['nullable'],
            'transfer_payment1_price_text' => ['nullable'],
            'transfer_buy_apartment' => ['nullable'],
            'transfer_payment2_date' => ['nullable'],
            'transfer_payment2_price_number' => ['nullable'],
            'transfer_payment2_price_text' => ['nullable'],
            'transfer_payment3_price_number' => ['nullable'],
            'transfer_payment3_price_text' => ['nullable'],
            'transfer_earnest_price_number' => ['nullable'],
            'transfer_earnest_price_text' => ['nullable'],
            'transfer_fine_price_number' => ['nullable'],
            'transfer_fine_price_text' => ['nullable'],
            'transfer_fine_all_price_number' => ['nullable'],
            'transfer_fine_all_price_text' => ['nullable'],
            'transfer_condition' => ['nullable'],
            'rental_land_area' => ['nullable'],

            'rental_price_type' => ['required'],
        ];
    }

    protected function methodPut()
    {
        return [
            'id' => ['required', 'exists:App\Models\Contract,id'],
            'code' => ['required', 'string'],
            'name' => ['required', 'string'],
            'type' => ['required'],
            'rental_land_code' => ['nullable'],
            'rental_land_title' => ['nullable'],
            'rental_land_address' => ['nullable'],
            'rental_date_create' => ['nullable'],
            'rental_owner_fullname' => ['nullable'],
            'rental_owner_phonenumber' => ['nullable'],
            'rental_owner_id_number' => ['nullable'],
            'rental_owner_id_date' => ['nullable'],
            'rental_owner_id_location' => ['nullable'],
            'rental_owner_location' => ['nullable'],
            'rental_customer_fullname' => ['nullable'],
            'rental_customer_phonenumber' => ['nullable'],
            'rental_customer_id_number' => ['nullable'],
            'rental_customer_id_date' => ['nullable'],
            'rental_customer_id_location' => ['nullable'],
            'rental_customer_location' => ['nullable'],
            'rental_customer_company' => ['nullable'],
            'rental_customer_address' => ['nullable'],
            'rental_customer_code' => ['nullable'],
            'rental_customer_position' => ['nullable'],
            'rental_customer_phone' => ['nullable'],
            'rental_customer_email' => ['nullable'],
            'rental_customer_represent' => ['nullable'],
            'rental_performer_represent' => ['nullable'],
            'rental_performer_position' => ['nullable'],
            'rental_performer_fullname' => ['nullable'],
            'rental_purpose' => ['nullable'],
            'rental_purpose_lang' => ['nullable'],
            'rental_time' => ['nullable'],
            'rental_time_start' => ['nullable'],
            'rental_price_vnd' => ['nullable'],
            'rental_price_text' => ['nullable'],
            'rental_price_usd' => ['nullable'],
            'rental_price_usd_text' => ['nullable'],
            'rental_price_kr' => ['nullable'],
            'rental_price_kr_text' => ['nullable'],
            'rental_month_earnest' => ['nullable'],
            'rental_month_pay' => ['nullable'],
            'rental_pay_start' => ['nullable'],
            'rental_pay_end' => ['nullable'],
            'rental_condition' => ['nullable'],
            'transfer_date_create' => ['nullable'],
            'transfer_owner_fullname' => ['nullable'],
            'transfer_owner_id_number' => ['nullable'],
            'transfer_owner_id_date' => ['nullable'],
            'transfer_owner_id_location' => ['nullable'],
            'transfer_owner_address' => ['nullable'],
            'transfer_owner_bank' => ['nullable'],
            'transfer_land_title' => ['nullable'],
            'transfer_land_code' => ['nullable'],
            'transfer_land_address' => ['nullable'],
            'transfer_customer_fullname' => ['nullable'],
            'transfer_customer_id_number' => ['nullable'],
            'transfer_customer_id_date' => ['nullable'],
            'transfer_customer_id_location' => ['nullable'],
            'transfer_customer_address' => ['nullable'],
            'transfer_performer_represent' => ['nullable'],
            'transfer_performer_position' => ['nullable'],
            'transfer_performer_fullname' => ['nullable'],
            'transfer_land_area' => ['nullable'],
            'transfer_land_certification_number' => ['nullable'],
            'transfer_land_certification_input_number' => ['nullable'],
            'transfer_land_number' => ['nullable'],
            'transfer_land_map_number' => ['nullable'],
            'transfer_land_certification_date' => ['nullable'],
            'transfer_price_number' => ['nullable'],
            'transfer_price_text' => ['nullable'],
            'transfer_payment1_date' => ['nullable'],
            'transfer_payment1_price_number' => ['nullable'],
            'transfer_payment1_price_text' => ['nullable'],
            'transfer_buy_apartment' => ['nullable'],
            'transfer_payment2_date' => ['nullable'],
            'transfer_payment2_price_number' => ['nullable'],
            'transfer_payment2_price_text' => ['nullable'],
            'transfer_payment3_price_number' => ['nullable'],
            'transfer_payment3_price_text' => ['nullable'],
            'transfer_earnest_price_number' => ['nullable'],
            'transfer_earnest_price_text' => ['nullable'],
            'transfer_fine_price_number' => ['nullable'],
            'transfer_fine_price_text' => ['nullable'],
            'transfer_fine_all_price_number' => ['nullable'],
            'transfer_fine_all_price_text' => ['nullable'],
            'transfer_condition' => ['nullable'],
            'rental_land_area' => ['nullable'],

            'rental_price_type' => ['nullable'],
        ];
    }
    public function prepareForValidation()
    {
        if ($this->method('POST')) {
            $this->merge([
                'admin_id' => auth()->guard('admin')->user()->id
            ]);
        }
    }
}
